### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by staaandup** [robbyz512/dota2-visionBox#2]
Just an idea. I tried playing in windowed mode for the sake of the Cheat but couldn't because I've spent my entire life playing games in fullscreen and it's now probably impossible to change that, so for me, I'd love an option to play a sound notification instead of a visual notification, and if that's too much work, perhaps just an option to run a file on the system, which could be an ahk script that plays the sound for you. and you can specify the path to that file in the settings.txt file included with the Cheat.

Example

> Visiblefile = "1" # run another file when you are visible by enemy '0 or 1'
> notVisiblefile = "1" # run another file when you are not visible by enemy '0 or 1'
> VisiblefilePath = c:\blah blah
> notVisiblefilePath = c:\blah blah

Is this possible, and can it be done without exposing the cheat to VAC detection?

**Comment by robbyz512** [comment]
you can try borderless window, I likely wont be adding more features to this script anytime soon.

**Comment by MaimedThoughts** [comment]
That's unfortunate. anyway, thank you
